steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args:
      - clean
      - package
      - -DskipTests

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args:
      - -c
      - |
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        SAFE_BRANCH=$(echo "${BRANCH_NAME}" | tr '/' '-')
        
        if [ "${BRANCH_NAME}" = "main" ]; then
         VERSION="$$TIMESTAMP"
        else
         VERSION="$${SAFE_BRANCH}-$${TIMESTAMP}"
        fi
        echo "Using image tag: $$VERSION"
        echo "$$VERSION" > /workspace/image-tag.txt
        docker build \
          -t asia-south1-docker.pkg.dev/$PROJECT_ID/one-step-repo/spring-dsl-flow:latest \
          -t asia-south1-docker.pkg.dev/$PROJECT_ID/one-step-repo/spring-dsl-flow:$$VERSION \
          .
        docker push asia-south1-docker.pkg.dev/$PROJECT_ID/one-step-repo/spring-dsl-flow:latest
        docker push asia-south1-docker.pkg.dev/$PROJECT_ID/one-step-repo/spring-dsl-flow:$$VERSION

  - name:  'gcr.io/cloud-builders/git'
    id: 'update-kustomization'
    entrypoint: bash
    args:
      - '-c'
      - |
        VERSION=$(cat /workspace/image-tag.txt)
        git config --global user.name "Cloud Build"
        git config --global user.email "noreply@company.com"
        
        # Update uat1 overlay with new image tag
        sed -i "s/newTag:.*/newTag: \"$$VERSION\"/" k8s/overlays/uat1/kustomization.yaml

        # Commit and push
        git add k8s/overlays/uat1/kustomization.yaml
        git commit -m "Update uat1 image tag to $${VERSION}

        Build ID: ${BUILD_ID}
        Commit SHA: ${COMMIT_SHA}" || echo "No changes to commit"

        git push origin ${BRANCH_NAME}
# we will use this later with substitution variable
#images:
#  - asia-south1-docker.pkg.dev/$PROJECT_ID/one-step-repo/spring-dsl-flow:latest

options:
  logging: CLOUD_LOGGING_ONLY