server:
  port: 8080

logging:
  level:
    root: INFO
#    enable below if we need to log/see the errors related to sftp connection
#    org.springframework.integration.sftp: TRACE
#    org.apache.sshd: DEBUG