apiVersion: v1
kind: Secret
metadata:
  name: sftp-private-key
  namespace: uat1
type: Opaque
data:
  id_rsa: 
    | 
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFB
    QUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJsd0FBQUFkemMyZ3RjbgpOaEFBQUFB
    d0VBQVFBQUFZRUF3dVFtaVBxMGlmNTNVeGY4eG5obU5zUFAwcjhzSjk0M3hGaUZBMnl3MGs3ZWxJ
    eGorc1orClE2cXp6ekU5VG50a1N5KzFXVU92UkI3dTJOSU5pNkhKOEtqSWErRlo0TTk2ZEhmMGoy
    cEJuS1ZhOFJQQWJtTG1NNTB5RkEKem5XSDRRQ0d0a0VNRTRxek1JbVhhRWpEd3J3dXFxTGY0ZGxK
    ZXVLaWtvSm8yek5sWE5HUi9VdUtrY1h5ZVJhMUUrWkVMegpwaWVhWElKU0NNL3NSTnl2ZkRoSHZU
    UUhHNEZUZkhUbGZ6dnVqVHBWUW1LMndLVm5qaUFPNVpEUXFoQitzVWJGekxxNkFZClpQUXdMdG13
    SWUxS016WXRDWHZxQUs3U2ZEU2lXMUg3dm5tUnpiaWliaUhEZmM1ZHMrVE5DWFdUQXRyelM4Um0z
    Sk9hQzEKa0pWcjhvLytqdE9VdVFDbkc4Q0szR0hBQUY2NnB6b1Y3SkRpMHFRaGZLWUQ4UCs5T2h4
    OWRQZFgvRTlkKzhDU0FmSUdEQwozZ2tXN3BLSEw5OWo1MFk5Y1pJaUlYNWJORDloSERxcXRqdkVI
    bGxZdFdyaStheDhWQXYzMlVnTm5TM2JLa0VJWUIrZFFPCnRFdUQyUmt1T09Ba0xRTUtqVmVoaGxS
    c05WWDZXUnBkK2ZzbHU2ci9BQUFGbUhIUHBRQnh6NlVBQUFBQUIzTnphQzF5YzIKRUFBQUdCQU1M
    a0pvajZ0SW4rZDFNWC9NWjRaamJEejlLL0xDZmVOOFJZaFFOc3NOSk8zcFNNWS9yR2ZrT3FzODh4
    UFU1NwpaRXN2dFZsRHIwUWU3dGpTRFl1aHlmQ295R3ZoV2VEUGVuUjM5STlxUVp5bFd2RVR3RzVp
    NWpPZE1oUU01MWgrRUFoclpCCkRCT0tzekNKbDJoSXc4SzhMcXFpMytIWlNYcmlvcEtDYU5zelpW
    elJrZjFMaXBIRjhua1d0UlBtUkM4NllubWx5Q1VnalAKN0VUY3IzdzRSNzAwQnh1QlUzeDA1WDg3
    N28wNlZVSml0c0NsWjQ0Z0R1V1EwS29RZnJGR3hjeTZ1Z0dHVDBNQzdac0NIdApTak0yTFFsNzZn
    Q3Uwbncwb2x0Uis3NTVrYzI0b200aHczM09YYlBrelFsMWt3TGE4MHZFWnR5VG1ndFpDVmEvS1Av
    bzdUCmxMa0FweHZBaXR4aHdBQmV1cWM2RmV5UTR0S2tJWHltQS9EL3ZUb2NmWFQzVi94UFhmdkFr
    Z0h5Qmd3dDRKRnU2U2h5L2YKWStkR1BYR1NJaUYrV3pRL1lSdzZxclk3eEI1WldMVnE0dm1zZkZR
    TDk5bElEWjB0MnlwQkNHQWZuVURyUkxnOWtaTGpqZwpKQzBEQ28xWG9ZWlViRFZWK2xrYVhmbjdK
    YnVxL3dBQUFBTUJBQUVBQUFHQU0zTzBVTG1QYkZjSC9hSDVsQlE1T0FBZUg4Cjlrd3VuQjQwNVRY
    NElVZEpGcDVlSGlpMVJZQlZsTnUwZU9uZWVwcE1mbG9ybGh6aVEwZm4yR0lmVUdzVWgrRVMwZlky
    Q2oKUFpobHNtOGsvMHdRWkZFSW5wdnhsbkxMdzh0Y1VGcUh0UkZWQzY5WFhLdE9lK1YwUE9tdHkv
    blVEK3hrdHRRTW9RallscwpVV0tTUWh6NTQ5dExyQXlNWlRkL2VzOXg5TjMvSFlxTStuQkxpUDhl
    WXBWaXd0bEYvbCtIYitLWDliRDJvdElvL2g3bkxOCk9MTHlVZTFZd1hhb0FCMzJ0S3F3Rzlub3do
    LzFBeWlTTGI0d0EweDhSdE1yV2kwMHNGbUVjazdyVks0UmhUUzRYSnN4WEcKeWY4bjBjaGtrbDZw
    K3dJVkJjM1dFMFhqeFNKRk5KdXRrL05EZkhianFmTTUwNDRjRUdOcEkwc0d3ZzJ0NStWNFNxOVpx
    NgpIN3JzcXpkTW55L0hlb1FsOUVWZ01nbjRoczBBQys5aVBwSEh4RVRpRkI5S3Jxb1NwUkp3T29r
    VDNvUkRqU016enF3QU02ClBPWk1oZGhLQXFZVmJHckx0Rlp3MW41OXBMNytBbURVUUxZMjFwT3p6
    RUtLU01jTVhGTFBtTE5sOGZwam1hOU4wUkFBQUEKd0FmZEJldmRibUYvM1ZjUGpVTkVOL0Y0WjNp
    WUdDZUZBZnVod3M5RFh4VExsM3lvQ1BXaGNNYUgxdVZqVm16TGNNdTR3Sgp0RkUzeVpYTThLNW5K
    MVZiVm1iaFVBUkpXTkF6UXduU1NvSGsvTzExWUNVeGJlODNBN1F5d2Q2ZzYwRjhaOUtwcnZLUURj
    Cmo4MVI2YmFJYytQZitNWXhwTm43dE9ZMkpSVmdqVjY4QmpmS2VqZnFWWmFmUUtOVndQR0NSTWh4
    UEROREtkZThUWFY4WVkKVGJIZWpSa2ZtKzVLQUloYkwwMkM0cW10b0JzS0hSYldFSGlGcytaODdO
    UkhEQStnQUFBTUVBMzkzZzA3WHgxbU1tVEtvagpEZHVQN2I1dVJ0UXhsR3o5a2hQM3hWSGlvRkw4
    QXFnR0trVDFkcWdJdnF1Wlc1NXF6ZVZSVEVKeTFmaDczekNBblNQODBaClAwRWZXeGR5WEd2dG5G
    S2k0N1hHYmJHaURrMDhlYnZTQTVaSDFTL0twSFBDY3V4Y3IrNVlKcEpwZjBVRjBMRDZrUHdQaDQK
    bHFLU3FMYnQ3YUV4Snlwd1pZWWwrbkpkZllZcDZjclg4TDR3MkJkbHJrQVBSRFhVWUFpbktoZHMw
    dVRtaXhFV1l1ZjMvbApOaHM2bnNLQWcwMUZvVTh2WjJNcFJYSWlKbTJBK0xBQUFBd1FEZTNZeXU2
    Ynp1UGpsQ2o0ZjlvczJFaHJGR2JidlptWGc0Clk2OWtSdk15b3lUSXo4T1l1clFUYTNMUnkrclpE
    d3JjemhHZEEwWVFGRW9pOG0xYjFETUVqUFRmQUJ1VGphWkZzRmYvaGYKQ3Q2cDQ4ZVo4STZHRzdE
    eEtDZmVrL0lpTnNnUnhzdzhBYzJnc0piSTVONnhITkxudlZ6QXEyem9tOVBHck1nWmVaTS9lUQpT
    aEJWWnkvVW9wRGgvekFBU29lTWtINzkrd3JEV3d5N1hUSGRiSTVpOFpZbTNBOVduYjdWUHFnZ3FU
    dXJ3aHRpOXRtS3A5CllQOEozY1MrWnF3TjBBQUFBaGNISmhZMmhwUUhCeVlXTm9hUzFVYUdsdWEx
    QmhaQzFVTlRjd0xWY3hNRVJIQVFJPQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
      